apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: userprofile:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:file:/data/h2/test;AUTO_SERVER=TRUE"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        volumeMounts:
        - name: h2-storage
          mountPath: /data/h2
      volumes:
      - name: h2-storage
        persistentVolumeClaim:
          claimName: h2-shared-pvc
